import { NextRequest, NextResponse } from 'next/server'
import { handleCors, requireAuth, json } from '@/lib/api-helpers'

// ============ POST - Generate PostgreSQL DDL from Prisma schema ============
export async function POST(request: NextRequest) {
  const corsResp = handleCors(request)
  if (corsResp) return corsResp

  const authUser = requireAuth(request)
  if (authUser instanceof Response) return authUser

  try {
    const body = await request.json()
    const { format } = body // 'ddl' | 'seed' | 'env' | 'schema'

    if (format === 'ddl') {
      return json({ data: { sql: generateDDL(), type: 'ddl' } })
    }
    if (format === 'seed') {
      return json({ data: { sql: generateSeedSQL(), type: 'seed' } })
    }
    if (format === 'env') {
      return json({ data: { sql: generateEnvConfig(body), type: 'env' } })
    }
    if (format === 'schema') {
      return json({ data: { sql: generatePrismaSchema(), type: 'schema' } })
    }

    // Default: return all
    return json({
      data: {
        ddl: generateDDL(),
        seed: generateSeedSQL(),
        env: generateEnvConfig(body),
        schema: generatePrismaSchema(),
      },
    })
  } catch (error) {
    console.error('[Database SQL Generation Error]', error)
    return json({ error: 'Failed to generate SQL.' }, 500)
  }
}

// ============ GET - Generate all SQL formats ============
export async function GET(request: NextRequest) {
  const corsResp = handleCors(request)
  if (corsResp) return corsResp

  const authUser = requireAuth(request)
  if (authUser instanceof Response) return authUser

  try {
    return json({
      data: {
        ddl: generateDDL(),
        seed: generateSeedSQL(),
        schema: generatePrismaSchema(),
      },
    })
  } catch (error) {
    console.error('[Database SQL Generation Error]', error)
    return json({ error: 'Failed to generate SQL.' }, 500)
  }
}

// ============ DDL Generation (PostgreSQL) ============
function generateDDL(): string {
  const statements: string[] = []

  statements.push(`-- ============================================`)
  statements.push(`-- PropNusa Database Schema - PostgreSQL`)
  statements.push(`-- Generated for Supabase`)
  statements.push(`-- ============================================`)
  statements.push(``)
  statements.push(`-- Enable UUID extension`)
  statements.push(`CREATE EXTENSION IF NOT EXISTS "uuid-ossp";`)
  statements.push(``)
  statements.push(`-- Set timezone`)
  statements.push(`SET timezone = 'Asia/Jakarta';`)
  statements.push(``)

  // ======= TABLES =======

  // User
  statements.push(`-- ============ USER & AUTH ============`)
  statements.push(`CREATE TABLE "User" (`)
  statements.push(`  "id" TEXT NOT NULL PRIMARY KEY,`)
  statements.push(`  "email" TEXT NOT NULL UNIQUE,`)
  statements.push(`  "name" TEXT NOT NULL,`)
  statements.push(`  "password" TEXT NOT NULL,`)
  statements.push(`  "phone" TEXT,`)
  statements.push(`  "avatar" TEXT,`)
  statements.push(`  "role" TEXT NOT NULL DEFAULT 'admin',`)
  statements.push(`  "isActive" BOOLEAN NOT NULL DEFAULT TRUE,`)
  statements.push(`  "lastLogin" TIMESTAMP(3),`)
  statements.push(`  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,`)
  statements.push(`  "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP`)
  statements.push(`);`)
  statements.push(``)

  // PropertyType
  statements.push(`-- ============ PROPERTY TYPE ============`)
  statements.push(`CREATE TABLE "PropertyType" (`)
  statements.push(`  "id" TEXT NOT NULL PRIMARY KEY,`)
  statements.push(`  "name" TEXT NOT NULL UNIQUE,`)
  statements.push(`  "slug" TEXT NOT NULL UNIQUE,`)
  statements.push(`  "icon" TEXT,`)
  statements.push(`  "description" TEXT,`)
  statements.push(`  "isActive" BOOLEAN NOT NULL DEFAULT TRUE,`)
  statements.push(`  "sortOrder" INTEGER NOT NULL DEFAULT 0,`)
  statements.push(`  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,`)
  statements.push(`  "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP`)
  statements.push(`);`)
  statements.push(``)

  // Province
  statements.push(`-- ============ PROVINCE ============`)
  statements.push(`CREATE TABLE "Province" (`)
  statements.push(`  "id" TEXT NOT NULL PRIMARY KEY,`)
  statements.push(`  "name" TEXT NOT NULL UNIQUE,`)
  statements.push(`  "slug" TEXT NOT NULL UNIQUE,`)
  statements.push(`  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,`)
  statements.push(`  "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP`)
  statements.push(`);`)
  statements.push(``)

  // City
  statements.push(`-- ============ CITY ============`)
  statements.push(`CREATE TABLE "City" (`)
  statements.push(`  "id" TEXT NOT NULL PRIMARY KEY,`)
  statements.push(`  "name" TEXT NOT NULL,`)
  statements.push(`  "slug" TEXT NOT NULL,`)
  statements.push(`  "provinceId" TEXT NOT NULL,`)
  statements.push(`  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,`)
  statements.push(`  "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,`)
  statements.push(`  CONSTRAINT "City_provinceId_fkey" FOREIGN KEY ("provinceId") REFERENCES "Province" ("id") ON DELETE RESTRICT ON UPDATE CASCADE`)
  statements.push(`);`)
  statements.push(``)

  // District
  statements.push(`-- ============ DISTRICT ============`)
  statements.push(`CREATE TABLE "District" (`)
  statements.push(`  "id" TEXT NOT NULL PRIMARY KEY,`)
  statements.push(`  "name" TEXT NOT NULL,`)
  statements.push(`  "slug" TEXT NOT NULL,`)
  statements.push(`  "cityId" TEXT NOT NULL,`)
  statements.push(`  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,`)
  statements.push(`  "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,`)
  statements.push(`  CONSTRAINT "District_cityId_fkey" FOREIGN KEY ("cityId") REFERENCES "City" ("id") ON DELETE RESTRICT ON UPDATE CASCADE`)
  statements.push(`);`)
  statements.push(``)

  // Village
  statements.push(`-- ============ VILLAGE ============`)
  statements.push(`CREATE TABLE "Village" (`)
  statements.push(`  "id" TEXT NOT NULL PRIMARY KEY,`)
  statements.push(`  "name" TEXT NOT NULL,`)
  statements.push(`  "slug" TEXT NOT NULL,`)
  statements.push(`  "districtId" TEXT NOT NULL,`)
  statements.push(`  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,`)
  statements.push(`  "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,`)
  statements.push(`  CONSTRAINT "Village_districtId_fkey" FOREIGN KEY ("districtId") REFERENCES "District" ("id") ON DELETE RESTRICT ON UPDATE CASCADE`)
  statements.push(`);`)
  statements.push(``)

  // Property
  statements.push(`-- ============ PROPERTY ============`)
  statements.push(`CREATE TABLE "Property" (`)
  statements.push(`  "id" TEXT NOT NULL PRIMARY KEY,`)
  statements.push(`  "code" TEXT NOT NULL UNIQUE,`)
  statements.push(`  "title" TEXT NOT NULL,`)
  statements.push(`  "slug" TEXT NOT NULL UNIQUE,`)
  statements.push(`  "description" TEXT NOT NULL,`)
  statements.push(`  "propertyTypeId" TEXT NOT NULL,`)
  statements.push(`  "status" TEXT NOT NULL DEFAULT 'draft',`)
  statements.push(`  "isFeatured" BOOLEAN NOT NULL DEFAULT FALSE,`)
  statements.push(`  "isNego" BOOLEAN NOT NULL DEFAULT FALSE,`)
  statements.push(`  "isNew" BOOLEAN NOT NULL DEFAULT FALSE,`)
  statements.push(`  "isPublished" BOOLEAN NOT NULL DEFAULT FALSE,`)
  statements.push(`  "price" BIGINT NOT NULL DEFAULT 0,`)
  statements.push(`  "priceDisplay" TEXT NOT NULL,`)
  statements.push(`  "provinceId" TEXT,`)
  statements.push(`  "cityId" TEXT,`)
  statements.push(`  "districtId" TEXT,`)
  statements.push(`  "villageId" TEXT,`)
  statements.push(`  "address" TEXT,`)
  statements.push(`  "latitude" DOUBLE PRECISION,`)
  statements.push(`  "longitude" DOUBLE PRECISION,`)
  statements.push(`  "landArea" INTEGER NOT NULL DEFAULT 0,`)
  statements.push(`  "buildingArea" INTEGER NOT NULL DEFAULT 0,`)
  statements.push(`  "bedrooms" INTEGER NOT NULL DEFAULT 0,`)
  statements.push(`  "bathrooms" INTEGER NOT NULL DEFAULT 0,`)
  statements.push(`  "garages" INTEGER NOT NULL DEFAULT 0,`)
  statements.push(`  "floors" INTEGER NOT NULL DEFAULT 0,`)
  statements.push(`  "electricity" TEXT,`)
  statements.push(`  "waterSource" TEXT,`)
  statements.push(`  "certificate" TEXT,`)
  statements.push(`  "buildingCond" TEXT,`)
  statements.push(`  "orientation" TEXT,`)
  statements.push(`  "facilities" TEXT,`)
  statements.push(`  "mainImage" TEXT,`)
  statements.push(`  "videoUrl" TEXT,`)
  statements.push(`  "virtualTourUrl" TEXT,`)
  statements.push(`  "metaTitle" TEXT,`)
  statements.push(`  "metaDescription" TEXT,`)
  statements.push(`  "metaKeywords" TEXT,`)
  statements.push(`  "agentId" TEXT,`)
  statements.push(`  "publishedAt" TIMESTAMP(3),`)
  statements.push(`  "deletedAt" TIMESTAMP(3),`)
  statements.push(`  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,`)
  statements.push(`  "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,`)
  statements.push(`  CONSTRAINT "Property_propertyTypeId_fkey" FOREIGN KEY ("propertyTypeId") REFERENCES "PropertyType" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,`)
  statements.push(`  CONSTRAINT "Property_provinceId_fkey" FOREIGN KEY ("provinceId") REFERENCES "Province" ("id") ON DELETE SET NULL ON UPDATE CASCADE,`)
  statements.push(`  CONSTRAINT "Property_cityId_fkey" FOREIGN KEY ("cityId") REFERENCES "City" ("id") ON DELETE SET NULL ON UPDATE CASCADE,`)
  statements.push(`  CONSTRAINT "Property_districtId_fkey" FOREIGN KEY ("districtId") REFERENCES "District" ("id") ON DELETE SET NULL ON UPDATE CASCADE,`)
  statements.push(`  CONSTRAINT "Property_villageId_fkey" FOREIGN KEY ("villageId") REFERENCES "Village" ("id") ON DELETE SET NULL ON UPDATE CASCADE,`)
  statements.push(`  CONSTRAINT "Property_agentId_fkey" FOREIGN KEY ("agentId") REFERENCES "User" ("id") ON DELETE SET NULL ON UPDATE CASCADE`)
  statements.push(`);`)
  statements.push(``)

  // PropertyImage
  statements.push(`-- ============ PROPERTY IMAGE ============`)
  statements.push(`CREATE TABLE "PropertyImage" (`)
  statements.push(`  "id" TEXT NOT NULL PRIMARY KEY,`)
  statements.push(`  "propertyId" TEXT NOT NULL,`)
  statements.push(`  "url" TEXT NOT NULL,`)
  statements.push(`  "altText" TEXT,`)
  statements.push(`  "sortOrder" INTEGER NOT NULL DEFAULT 0,`)
  statements.push(`  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,`)
  statements.push(`  CONSTRAINT "PropertyImage_propertyId_fkey" FOREIGN KEY ("propertyId") REFERENCES "Property" ("id") ON DELETE CASCADE ON UPDATE CASCADE`)
  statements.push(`);`)
  statements.push(``)

  // Lead
  statements.push(`-- ============ LEAD ============`)
  statements.push(`CREATE TABLE "Lead" (`)
  statements.push(`  "id" TEXT NOT NULL PRIMARY KEY,`)
  statements.push(`  "name" TEXT NOT NULL,`)
  statements.push(`  "whatsapp" TEXT NOT NULL,`)
  statements.push(`  "email" TEXT,`)
  statements.push(`  "phone" TEXT,`)
  statements.push(`  "propertyId" TEXT,`)
  statements.push(`  "propertyName" TEXT,`)
  statements.push(`  "locationInterest" TEXT,`)
  statements.push(`  "budget" TEXT,`)
  statements.push(`  "propertyTypeInterest" TEXT,`)
  statements.push(`  "needType" TEXT NOT NULL DEFAULT 'beli',`)
  statements.push(`  "source" TEXT NOT NULL DEFAULT 'website',`)
  statements.push(`  "status" TEXT NOT NULL DEFAULT 'baru',`)
  statements.push(`  "notes" TEXT,`)
  statements.push(`  "dpAmount" TEXT,`)
  statements.push(`  "promo" TEXT,`)
  statements.push(`  "agentId" TEXT,`)
  statements.push(`  "nextFollowUp" TIMESTAMP(3),`)
  statements.push(`  "followUpNotes" TEXT,`)
  statements.push(`  "deletedAt" TIMESTAMP(3),`)
  statements.push(`  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,`)
  statements.push(`  "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,`)
  statements.push(`  CONSTRAINT "Lead_propertyId_fkey" FOREIGN KEY ("propertyId") REFERENCES "Property" ("id") ON DELETE SET NULL ON UPDATE CASCADE,`)
  statements.push(`  CONSTRAINT "Lead_agentId_fkey" FOREIGN KEY ("agentId") REFERENCES "User" ("id") ON DELETE SET NULL ON UPDATE CASCADE`)
  statements.push(`);`)
  statements.push(``)

  // ArticleCategory
  statements.push(`-- ============ ARTICLE CATEGORY ============`)
  statements.push(`CREATE TABLE "ArticleCategory" (`)
  statements.push(`  "id" TEXT NOT NULL PRIMARY KEY,`)
  statements.push(`  "name" TEXT NOT NULL UNIQUE,`)
  statements.push(`  "slug" TEXT NOT NULL UNIQUE,`)
  statements.push(`  "description" TEXT,`)
  statements.push(`  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,`)
  statements.push(`  "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP`)
  statements.push(`);`)
  statements.push(``)

  // Article
  statements.push(`-- ============ ARTICLE ============`)
  statements.push(`CREATE TABLE "Article" (`)
  statements.push(`  "id" TEXT NOT NULL PRIMARY KEY,`)
  statements.push(`  "title" TEXT NOT NULL,`)
  statements.push(`  "slug" TEXT NOT NULL UNIQUE,`)
  statements.push(`  "content" TEXT NOT NULL,`)
  statements.push(`  "excerpt" TEXT,`)
  statements.push(`  "categoryId" TEXT,`)
  statements.push(`  "tags" TEXT,`)
  statements.push(`  "featuredImage" TEXT,`)
  statements.push(`  "isPublished" BOOLEAN NOT NULL DEFAULT FALSE,`)
  statements.push(`  "publishedAt" TIMESTAMP(3),`)
  statements.push(`  "scheduledAt" TIMESTAMP(3),`)
  statements.push(`  "metaTitle" TEXT,`)
  statements.push(`  "metaDescription" TEXT,`)
  statements.push(`  "metaKeywords" TEXT,`)
  statements.push(`  "canonicalUrl" TEXT,`)
  statements.push(`  "authorId" TEXT,`)
  statements.push(`  "viewCount" INTEGER NOT NULL DEFAULT 0,`)
  statements.push(`  "deletedAt" TIMESTAMP(3),`)
  statements.push(`  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,`)
  statements.push(`  "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,`)
  statements.push(`  CONSTRAINT "Article_categoryId_fkey" FOREIGN KEY ("categoryId") REFERENCES "ArticleCategory" ("id") ON DELETE SET NULL ON UPDATE CASCADE,`)
  statements.push(`  CONSTRAINT "Article_authorId_fkey" FOREIGN KEY ("authorId") REFERENCES "User" ("id") ON DELETE SET NULL ON UPDATE CASCADE`)
  statements.push(`);`)
  statements.push(``)

  // AgentProfile
  statements.push(`-- ============ AGENT PROFILE ============`)
  statements.push(`CREATE TABLE "AgentProfile" (`)
  statements.push(`  "id" TEXT NOT NULL PRIMARY KEY,`)
  statements.push(`  "userId" TEXT NOT NULL UNIQUE,`)
  statements.push(`  "name" TEXT NOT NULL,`)
  statements.push(`  "title" TEXT,`)
  statements.push(`  "photo" TEXT,`)
  statements.push(`  "whatsapp" TEXT NOT NULL,`)
  statements.push(`  "email" TEXT,`)
  statements.push(`  "bio" TEXT,`)
  statements.push(`  "areaSpec" TEXT,`)
  statements.push(`  "isActive" BOOLEAN NOT NULL DEFAULT TRUE,`)
  statements.push(`  "sortOrder" INTEGER NOT NULL DEFAULT 0,`)
  statements.push(`  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,`)
  statements.push(`  "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,`)
  statements.push(`  CONSTRAINT "AgentProfile_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User" ("id") ON DELETE RESTRICT ON UPDATE CASCADE`)
  statements.push(`);`)
  statements.push(``)

  // WebsiteSetting
  statements.push(`-- ============ WEBSITE SETTINGS ============`)
  statements.push(`CREATE TABLE "WebsiteSetting" (`)
  statements.push(`  "id" TEXT NOT NULL PRIMARY KEY,`)
  statements.push(`  "key" TEXT NOT NULL UNIQUE,`)
  statements.push(`  "value" TEXT NOT NULL,`)
  statements.push(`  "group" TEXT NOT NULL DEFAULT 'general',`)
  statements.push(`  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,`)
  statements.push(`  "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP`)
  statements.push(`);`)
  statements.push(``)

  // Media
  statements.push(`-- ============ MEDIA ============`)
  statements.push(`CREATE TABLE "Media" (`)
  statements.push(`  "id" TEXT NOT NULL PRIMARY KEY,`)
  statements.push(`  "filename" TEXT NOT NULL,`)
  statements.push(`  "url" TEXT NOT NULL,`)
  statements.push(`  "mimeType" TEXT NOT NULL,`)
  statements.push(`  "size" INTEGER NOT NULL DEFAULT 0,`)
  statements.push(`  "altText" TEXT,`)
  statements.push(`  "folder" TEXT NOT NULL DEFAULT '/',`)
  statements.push(`  "deletedAt" TIMESTAMP(3),`)
  statements.push(`  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,`)
  statements.push(`  "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP`)
  statements.push(`);`)
  statements.push(``)

  // ActivityLog
  statements.push(`-- ============ ACTIVITY LOG ============`)
  statements.push(`CREATE TABLE "ActivityLog" (`)
  statements.push(`  "id" TEXT NOT NULL PRIMARY KEY,`)
  statements.push(`  "userId" TEXT NOT NULL,`)
  statements.push(`  "action" TEXT NOT NULL,`)
  statements.push(`  "entity" TEXT,`)
  statements.push(`  "entityId" TEXT,`)
  statements.push(`  "details" TEXT,`)
  statements.push(`  "ipAddress" TEXT,`)
  statements.push(`  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,`)
  statements.push(`  CONSTRAINT "ActivityLog_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User" ("id") ON DELETE RESTRICT ON UPDATE CASCADE`)
  statements.push(`);`)
  statements.push(``)

  // ======= INDEXES =======
  statements.push(`-- ============ INDEXES ============`)
  const indexes = [
    `CREATE INDEX "Property_slug_idx" ON "Property"("slug");`,
    `CREATE INDEX "Property_status_idx" ON "Property"("status");`,
    `CREATE INDEX "Property_propertyTypeId_idx" ON "Property"("propertyTypeId");`,
    `CREATE INDEX "Property_cityId_idx" ON "Property"("cityId");`,
    `CREATE INDEX "Property_districtId_idx" ON "Property"("districtId");`,
    `CREATE INDEX "Property_isFeatured_idx" ON "Property"("isFeatured");`,
    `CREATE INDEX "Property_isPublished_idx" ON "Property"("isPublished");`,
    `CREATE INDEX "Property_price_idx" ON "Property"("price");`,
    `CREATE INDEX "PropertyImage_propertyId_idx" ON "PropertyImage"("propertyId");`,
    `CREATE INDEX "Lead_status_idx" ON "Lead"("status");`,
    `CREATE INDEX "Lead_agentId_idx" ON "Lead"("agentId");`,
    `CREATE INDEX "Lead_source_idx" ON "Lead"("source");`,
    `CREATE INDEX "Lead_createdAt_idx" ON "Lead"("createdAt");`,
    `CREATE INDEX "Article_slug_idx" ON "Article"("slug");`,
    `CREATE INDEX "Article_categoryId_idx" ON "Article"("categoryId");`,
    `CREATE INDEX "Article_isPublished_idx" ON "Article"("isPublished");`,
    `CREATE INDEX "Article_createdAt_idx" ON "Article"("createdAt");`,
    `CREATE INDEX "AgentProfile_isActive_idx" ON "AgentProfile"("isActive");`,
    `CREATE INDEX "WebsiteSetting_group_idx" ON "WebsiteSetting"("group");`,
    `CREATE INDEX "Media_folder_idx" ON "Media"("folder");`,
    `CREATE INDEX "ActivityLog_userId_idx" ON "ActivityLog"("userId");`,
    `CREATE INDEX "ActivityLog_action_idx" ON "ActivityLog"("action");`,
    `CREATE INDEX "ActivityLog_createdAt_idx" ON "ActivityLog"("createdAt");`,
  ]
  statements.push(...indexes)
  statements.push(``)

  // ======= TRIGGER FOR updatedAt =======
  statements.push(`-- ============ UPDATEDAT TRIGGER ============`)
  statements.push(`CREATE OR REPLACE FUNCTION update_updated_at_column()`)
  statements.push(`RETURNS TRIGGER AS $$`)
  statements.push(`BEGIN`)
  statements.push(`  NEW."updatedAt" = CURRENT_TIMESTAMP;`)
  statements.push(`  RETURN NEW;`)
  statements.push(`END;`)
  statements.push(`$$ LANGUAGE plpgsql;`)
  statements.push(``)

  const tables = [
    'User', 'PropertyType', 'Province', 'City', 'District', 'Village',
    'Property', 'PropertyImage', 'Lead', 'ArticleCategory', 'Article',
    'AgentProfile', 'WebsiteSetting', 'Media', 'ActivityLog'
  ]
  for (const table of tables) {
    statements.push(`CREATE TRIGGER "${table}_updatedAt"`)
    statements.push(`  BEFORE UPDATE ON "${table}"`)
    statements.push(`  FOR EACH ROW`)
    statements.push(`  EXECUTE FUNCTION update_updated_at_column();`)
    statements.push(``)
  }

  statements.push(`-- ============ DONE ============`)
  statements.push(`-- Semua tabel berhasil dibuat!`)
  statements.push(`-- Jalankan seed data terpisah untuk mengisi data awal.`)

  return statements.join('\n')
}

// ============ Seed SQL Generation ============
function generateSeedSQL(): string {
  const s: string[] = []

  s.push(`-- ============================================`)
  s.push(`-- PropNusa Seed Data - PostgreSQL`)
  s.push(`-- Jalankan setelah DDL di atas`)
  s.push(`-- ============================================`)
  s.push(``)

  // Property Types
  s.push(`-- ============ PROPERTY TYPES ============`)
  s.push(`INSERT INTO "PropertyType" ("id", "name", "slug", "isActive", "sortOrder") VALUES`)
  s.push(`  ('pt-1', 'Rumah', 'rumah', TRUE, 1),`)
  s.push(`  ('pt-2', 'Tanah', 'tanah', TRUE, 2),`)
  s.push(`  ('pt-3', 'Ruko', 'ruko', TRUE, 3),`)
  s.push(`  ('pt-4', 'Apartemen', 'apartemen', TRUE, 4),`)
  s.push(`  ('pt-5', 'Villa', 'villa', TRUE, 5),`)
  s.push(`  ('pt-6', 'Gudang', 'gudang', TRUE, 6),`)
  s.push(`  ('pt-7', 'Kantor', 'kantor', TRUE, 7),`)
  s.push(`  ('pt-8', 'Kost', 'kost', TRUE, 8),`)
  s.push(`  ('pt-9', 'Pabrik', 'pabrik', TRUE, 9),`)
  s.push(`  ('pt-10', 'Kavling', 'kavling', TRUE, 10),`)
  s.push(`  ('pt-11', 'Komersial', 'komersial', TRUE, 11);`)
  s.push(``)

  // Provinces
  s.push(`-- ============ PROVINCES ============`)
  s.push(`INSERT INTO "Province" ("id", "name", "slug") VALUES`)
  s.push(`  ('prov-1', 'Jawa Barat', 'jawa-barat'),`)
  s.push(`  ('prov-2', 'Jawa Timur', 'jawa-timur'),`)
  s.push(`  ('prov-3', 'Bali', 'bali');`)
  s.push(``)

  // Cities
  s.push(`-- ============ CITIES ============`)
  s.push(`INSERT INTO "City" ("id", "name", "slug", "provinceId") VALUES`)
  s.push(`  ('city-1', 'Bandung', 'bandung', 'prov-1'),`)
  s.push(`  ('city-2', 'Bogor', 'bogor', 'prov-1'),`)
  s.push(`  ('city-3', 'Surabaya', 'surabaya', 'prov-2'),`)
  s.push(`  ('city-4', 'Malang', 'malang', 'prov-2'),`)
  s.push(`  ('city-5', 'Denpasar', 'denpasar', 'prov-3');`)
  s.push(``)

  // Districts
  s.push(`-- ============ DISTRICTS ============`)
  s.push(`INSERT INTO "District" ("id", "name", "slug", "cityId") VALUES`)
  s.push(`  ('dist-1', 'Coblong', 'coblong', 'city-1'),`)
  s.push(`  ('dist-2', 'Cidadap', 'cidadap', 'city-1'),`)
  s.push(`  ('dist-3', 'Cimahi', 'cimahi', 'city-2'),`)
  s.push(`  ('dist-4', 'Gubeng', 'gubeng', 'city-3'),`)
  s.push(`  ('dist-5', 'Kuta', 'kuta', 'city-5'),`)
  s.push(`  ('dist-6', 'Ubud', 'ubud', 'city-5');`)
  s.push(``)

  // Villages
  s.push(`-- ============ VILLAGES ============`)
  s.push(`INSERT INTO "Village" ("id", "name", "slug", "districtId") VALUES`)
  s.push(`  ('vill-1', 'Dago', 'dago', 'dist-1'),`)
  s.push(`  ('vill-2', 'Lebakgede', 'lebakgede', 'dist-1'),`)
  s.push(`  ('vill-3', 'Cimahi Utara', 'cimahi-utara', 'dist-3');`)
  s.push(``)

  // Admin user (password: admin123 bcrypt hash)
  s.push(`-- ============ ADMIN USER ============`)
  s.push(`-- Password: admin123`)
  s.push(`INSERT INTO "User" ("id", "email", "name", "password", "role", "isActive") VALUES`)
  s.push(`  ('user-admin', 'admin@properti.com', 'Administrator', '$2a$10$rJvN4K3J6J7J7J7J7J7J7OeQv6J7J7J7J7J7J7J7J7J7J7J7', 'super_admin', TRUE),`)
  s.push(`  ('user-agent1', 'agen1@properti.com', 'Budi Santoso', '$2a$10$rJvN4K3J6J7J7J7J7J7J7OeQv6J7J7J7J7J7J7J7J7J7J7', 'agent', TRUE);`)
  s.push(``)
  s.push(`-- NOTE: Hash di atas adalah placeholder. Ganti dengan hash bcrypt yang benar.`)
  s.push(`-- Gunakan: npx prisma db seed -- atau generate hash dari backend.`)
  s.push(``)

  // Website Settings
  s.push(`-- ============ WEBSITE SETTINGS ============`)
  s.push(`INSERT INTO "WebsiteSetting" ("id", "key", "value", "group") VALUES`)
  s.push(`  ('ws-1', 'site_name', 'PropNusa', 'general'),`)
  s.push(`  ('ws-2', 'site_tagline', 'Jual Beli Properti Terpercaya', 'general'),`)
  s.push(`  ('ws-3', 'site_description', 'Platform jual beli properti terpercaya di Indonesia', 'general'),`)
  s.push(`  ('ws-4', 'contact_phone', '+62 812 3456 7890', 'contact'),`)
  s.push(`  ('ws-5', 'contact_whatsapp', '+62 812 3456 7890', 'contact'),`)
  s.push(`  ('ws-6', 'contact_email', 'info@propnusa.com', 'contact'),`)
  s.push(`  ('ws-7', 'contact_address', 'Jl. Properti No. 1, Jakarta', 'contact'),`)
  s.push(`  ('ws-8', 'contact_working_hours', 'Sen-Sab 09:00-17:00', 'contact'),`)
  s.push(`  ('ws-9', 'seo_meta_title', 'PropNusa - Jual Beli Properti Terpercaya', 'seo'),`)
  s.push(`  ('ws-10', 'seo_meta_description', 'Platform jual beli properti terpercaya', 'seo'),`)
  s.push(`  ('ws-11', 'seo_robots', 'index, follow', 'seo'),`)
  s.push(`  ('ws-12', 'social_facebook', 'https://facebook.com/propnusa', 'social'),`)
  s.push(`  ('ws-13', 'social_instagram', 'https://instagram.com/propnusa', 'social'),`)
  s.push(`  ('ws-14', 'social_youtube', 'https://youtube.com/@propnusa', 'social'),`)
  s.push(`  ('ws-15', 'social_tiktok', 'https://tiktok.com/@propnusa', 'social');`)
  s.push(``)

  // Article Categories
  s.push(`-- ============ ARTICLE CATEGORIES ============`)
  s.push(`INSERT INTO "ArticleCategory" ("id", "name", "slug") VALUES`)
  s.push(`  ('ac-1', 'Tips Properti', 'tips-properti'),`)
  s.push(`  ('ac-2', 'Berita Properti', 'berita-properti'),`)
  s.push(`  ('ac-3', 'Panduan KPR', 'panduan-kpr'),`)
  s.push(`  ('ac-4', 'Investasi', 'investasi'),`)
  s.push(`  ('ac-5', 'Hukum Properti', 'hukum-properti');`)
  s.push(``)

  // Agent Profiles
  s.push(`-- ============ AGENT PROFILES ============`)
  s.push(`INSERT INTO "AgentProfile" ("id", "userId", "name", "whatsapp", "bio", "isActive") VALUES`)
  s.push(`  ('ap-1', 'user-agent1', 'Budi Santoso', '+62 812 3456 7890', 'Agent properti berpengalaman 5 tahun', TRUE);`)
  s.push(``)

  s.push(`-- ============ SEED DONE ============`)

  return s.join('\n')
}

// ============ ENV Config Generation ============
function generateEnvConfig(body: Record<string, unknown>): string {
  const host = (body.host as string) || 'db.xxxxx.supabase.co'
  const port = (body.port as string) || '5432'
  const name = (body.name as string) || 'postgres'
  const user = (body.user as string) || 'postgres.xxxxx'
  const password = (body.password as string) || 'your-password-here'
  const pool = (body.pool as string) || '10'

  const connectionString = `postgresql://${user}:${password}@${host}:${port}/${name}?pgbouncer=true&connect_timeout=15`

  const lines: string[] = []
  lines.push(`# ============================================`)
  lines.push(`# PropNusa Environment Variables`)
  lines.push(`# Database: Supabase (PostgreSQL)`)
  lines.push(`# ============================================`)
  lines.push(``)
  lines.push(`# Database Connection (Supabase)`)
  lines.push(`DATABASE_URL="${connectionString}"`)
  lines.push(``)
  lines.push(`# Direct connection (untuk migration)`)
  lines.push(`DIRECT_URL="postgresql://${user}:${password}@${host}:${port}/${name}?connect_timeout=15"`)
  lines.push(``)
  lines.push(`# Connection Pool (Supabase Pooler)`)
  lines.push(`DATABASE_URL_POOL="${connectionString}"`)
  lines.push(``)
  lines.push(`# App Config`)
  lines.push(`NEXT_PUBLIC_APP_URL="https://www.propnusa.com"`)
  lines.push(`NEXTAUTH_SECRET="your-secret-key-min-32-characters"`)
  lines.push(`NEXTAUTH_URL="https://www.propnusa.com"`)
  lines.push(``)
  lines.push(`# Connection Pool Size`)
  lines.push(`DATABASE_POOL_SIZE=${pool}`)

  return lines.join('\n')
}

// ============ Prisma Schema for PostgreSQL ============
function generatePrismaSchema(): string {
  const s: string[] = []
  s.push(`// ============================================`)
  s.push(`// PropNusa Prisma Schema - PostgreSQL / Supabase`)
  s.push(`// Ganti file prisma/schema.prisma dengan ini`)
  s.push(`// Lalu jalankan: npx prisma db push`)
  s.push(`// ============================================`)
  s.push(``)
  s.push(`generator client {`)
  s.push(`  provider = "prisma-client-js"`)
  s.push(`}`)
  s.push(``)
  s.push(`datasource db {`)
  s.push(`  provider  = "postgresql"`)
  s.push(`  url       = env("DATABASE_URL")`)
  s.push(`  directUrl = env("DIRECT_URL")`)
  s.push(`}`)
  s.push(``)
  s.push(`// ============ USER & AUTH ============`)
  s.push(`model User {`)
  s.push(`  id            String   @id @default(cuid())`)
  s.push(`  email         String   @unique`)
  s.push(`  name          String`)
  s.push(`  password      String`)
  s.push(`  phone         String?`)
  s.push(`  avatar        String?`)
  s.push(`  role          String   @default("admin")`)
  s.push(`  isActive      Boolean  @default(true)`)
  s.push(`  lastLogin     DateTime?`)
  s.push(`  createdAt     DateTime @default(now())`)
  s.push(`  updatedAt     DateTime @updatedAt`)
  s.push(``)
  s.push(`  properties   Property[] @relation("AgentProperties")`)
  s.push(`  leads        Lead[]`)
  s.push(`  articles     Article[]`)
  s.push(`  activityLogs ActivityLog[]`)
  s.push(`  agentProfile AgentProfile?`)
  s.push(`}`)
  s.push(``)
  s.push(`// ============ PROPERTY TYPE ============`)
  s.push(`model PropertyType {`)
  s.push(`  id          String   @id @default(cuid())`)
  s.push(`  name        String   @unique`)
  s.push(`  slug        String   @unique`)
  s.push(`  icon        String?`)
  s.push(`  description String?`)
  s.push(`  isActive    Boolean  @default(true)`)
  s.push(`  sortOrder   Int      @default(0)`)
  s.push(`  createdAt   DateTime @default(now())`)
  s.push(`  updatedAt   DateTime @updatedAt`)
  s.push(``)
  s.push(`  properties Property[]`)
  s.push(`}`)
  s.push(``)
  s.push(`// ============ LOCATION HIERARCHY ============`)
  s.push(`model Province {`)
  s.push(`  id        String   @id @default(cuid())`)
  s.push(`  name      String   @unique`)
  s.push(`  slug      String   @unique`)
  s.push(`  createdAt DateTime @default(now())`)
  s.push(`  updatedAt DateTime @updatedAt`)
  s.push(``)
  s.push(`  cities     City[]`)
  s.push(`  properties Property[]`)
  s.push(`}`)
  s.push(``)
  s.push(`model City {`)
  s.push(`  id         String   @id @default(cuid())`)
  s.push(`  name       String`)
  s.push(`  slug       String`)
  s.push(`  provinceId String`)
  s.push(`  createdAt  DateTime @default(now())`)
  s.push(`  updatedAt  DateTime @updatedAt`)
  s.push(``)
  s.push(`  province  Province  @relation(fields: [provinceId], references: [id])`)
  s.push(`  districts District[]`)
  s.push(`  properties Property[]`)
  s.push(`}`)
  s.push(``)
  s.push(`model District {`)
  s.push(`  id        String   @id @default(cuid())`)
  s.push(`  name      String`)
  s.push(`  slug      String`)
  s.push(`  cityId    String`)
  s.push(`  createdAt DateTime @default(now())`)
  s.push(`  updatedAt DateTime @updatedAt`)
  s.push(``)
  s.push(`  city     City     @relation(fields: [cityId], references: [id])`)
  s.push(`  villages Village[]`)
  s.push(`  properties Property[]`)
  s.push(`}`)
  s.push(``)
  s.push(`model Village {`)
  s.push(`  id         String   @id @default(cuid())`)
  s.push(`  name       String`)
  s.push(`  slug       String`)
  s.push(`  districtId String`)
  s.push(`  createdAt DateTime @default(now())`)
  s.push(`  updatedAt DateTime @updatedAt`)
  s.push(``)
  s.push(`  district  District  @relation(fields: [districtId], references: [id])`)
  s.push(`  properties Property[]`)
  s.push(`}`)
  s.push(``)
  s.push(`// ============ PROPERTY ============`)
  s.push(`model Property {`)
  s.push(`  id              String   @id @default(cuid())`)
  s.push(`  code            String   @unique`)
  s.push(`  title           String`)
  s.push(`  slug            String   @unique`)
  s.push(`  description     String`)
  s.push(`  propertyTypeId  String`)
  s.push(`  status          String   @default("draft")`)
  s.push(`  isFeatured      Boolean  @default(false)`)
  s.push(`  isNego          Boolean  @default(false)`)
  s.push(`  isNew           Boolean  @default(false)`)
  s.push(`  isPublished     Boolean  @default(false)`)
  s.push(`  price           BigInt   @default(0)`)
  s.push(`  priceDisplay    String`)
  s.push(`  provinceId      String?`)
  s.push(`  cityId          String?`)
  s.push(`  districtId      String?`)
  s.push(`  villageId       String?`)
  s.push(`  address         String?`)
  s.push(`  latitude        Float?`)
  s.push(`  longitude       Float?`)
  s.push(`  landArea        Int      @default(0)`)
  s.push(`  buildingArea    Int      @default(0)`)
  s.push(`  bedrooms        Int      @default(0)`)
  s.push(`  bathrooms       Int      @default(0)`)
  s.push(`  garages         Int      @default(0)`)
  s.push(`  floors          Int      @default(0)`)
  s.push(`  electricity     String?`)
  s.push(`  waterSource     String?`)
  s.push(`  certificate     String?`)
  s.push(`  buildingCond    String?`)
  s.push(`  orientation     String?`)
  s.push(`  facilities      String?`)
  s.push(`  mainImage       String?`)
  s.push(`  videoUrl        String?`)
  s.push(`  virtualTourUrl  String?`)
  s.push(`  metaTitle       String?`)
  s.push(`  metaDescription String?`)
  s.push(`  metaKeywords    String?`)
  s.push(`  agentId         String?`)
  s.push(`  publishedAt     DateTime?`)
  s.push(`  deletedAt       DateTime?`)
  s.push(`  createdAt       DateTime @default(now())`)
  s.push(`  updatedAt       DateTime @updatedAt`)
  s.push(``)
  s.push(`  propertyType PropertyType @relation(fields: [propertyTypeId], references: [id])`)
  s.push(`  province      Province?  @relation(fields: [provinceId], references: [id])`)
  s.push(`  city          City?      @relation(fields: [cityId], references: [id])`)
  s.push(`  district      District?  @relation(fields: [districtId], references: [id])`)
  s.push(`  village       Village?   @relation(fields: [villageId], references: [id])`)
  s.push(`  agent         User?      @relation("AgentProperties", fields: [agentId], references: [id])`)
  s.push(`  images        PropertyImage[]`)
  s.push(`  leads         Lead[]`)
  s.push(``)
  s.push(`  @@index([slug])`)
  s.push(`  @@index([status])`)
  s.push(`  @@index([propertyTypeId])`)
  s.push(`  @@index([cityId])`)
  s.push(`  @@index([districtId])`)
  s.push(`  @@index([isFeatured])`)
  s.push(`  @@index([isPublished])`)
  s.push(`  @@index([price])`)
  s.push(`}`)
  s.push(``)
  s.push(`// ============ PROPERTY IMAGE ============`)
  s.push(`model PropertyImage {`)
  s.push(`  id         String   @id @default(cuid())`)
  s.push(`  propertyId String`)
  s.push(`  url        String`)
  s.push(`  altText    String?`)
  s.push(`  sortOrder  Int      @default(0)`)
  s.push(`  createdAt  DateTime @default(now())`)
  s.push(``)
  s.push(`  property Property @relation(fields: [propertyId], references: [id], onDelete: Cascade)`)
  s.push(``)
  s.push(`  @@index([propertyId])`)
  s.push(`}`)
  s.push(``)
  s.push(`// ============ LEAD ============`)
  s.push(`model Lead {`)
  s.push(`  id              String   @id @default(cuid())`)
  s.push(`  name            String`)
  s.push(`  whatsapp        String`)
  s.push(`  email           String?`)
  s.push(`  phone           String?`)
  s.push(`  propertyId      String?`)
  s.push(`  propertyName    String?`)
  s.push(`  locationInterest String?`)
  s.push(`  budget          String?`)
  s.push(`  propertyTypeInterest String?`)
  s.push(`  needType        String   @default("beli")`)
  s.push(`  source          String   @default("website")`)
  s.push(`  status          String   @default("baru")`)
  s.push(`  notes           String?`)
  s.push(`  dpAmount        String?`)
  s.push(`  promo           String?`)
  s.push(`  agentId         String?`)
  s.push(`  nextFollowUp    DateTime?`)
  s.push(`  followUpNotes   String?`)
  s.push(`  deletedAt       DateTime?`)
  s.push(`  createdAt       DateTime @default(now())`)
  s.push(`  updatedAt       DateTime @updatedAt`)
  s.push(``)
  s.push(`  property Property? @relation(fields: [propertyId], references: [id])`)
  s.push(`  agent    User?     @relation(fields: [agentId], references: [id])`)
  s.push(``)
  s.push(`  @@index([status])`)
  s.push(`  @@index([agentId])`)
  s.push(`  @@index([source])`)
  s.push(`  @@index([createdAt])`)
  s.push(`}`)
  s.push(``)
  s.push(`// ============ ARTICLE ============`)
  s.push(`model Article {`)
  s.push(`  id            String   @id @default(cuid())`)
  s.push(`  title         String`)
  s.push(`  slug          String   @unique`)
  s.push(`  content       String`)
  s.push(`  excerpt       String?`)
  s.push(`  categoryId    String?`)
  s.push(`  tags          String?`)
  s.push(`  featuredImage String?`)
  s.push(`  isPublished   Boolean  @default(false)`)
  s.push(`  publishedAt   DateTime?`)
  s.push(`  scheduledAt   DateTime?`)
  s.push(`  metaTitle       String?`)
  s.push(`  metaDescription String?`)
  s.push(`  metaKeywords    String?`)
  s.push(`  canonicalUrl    String?`)
  s.push(`  authorId      String?`)
  s.push(`  viewCount     Int      @default(0)`)
  s.push(`  deletedAt     DateTime?`)
  s.push(`  createdAt     DateTime @default(now())`)
  s.push(`  updatedAt     DateTime @updatedAt`)
  s.push(``)
  s.push(`  category ArticleCategory? @relation(fields: [categoryId], references: [id])`)
  s.push(`  author   User?            @relation(fields: [authorId], references: [id])`)
  s.push(``)
  s.push(`  @@index([slug])`)
  s.push(`  @@index([categoryId])`)
  s.push(`  @@index([isPublished])`)
  s.push(`  @@index([createdAt])`)
  s.push(`}`)
  s.push(``)
  s.push(`// ============ ARTICLE CATEGORY ============`)
  s.push(`model ArticleCategory {`)
  s.push(`  id        String     @id @default(cuid())`)
  s.push(`  name      String     @unique`)
  s.push(`  slug      String     @unique`)
  s.push(`  description String?`)
  s.push(`  createdAt DateTime   @default(now())`)
  s.push(`  updatedAt DateTime   @updatedAt`)
  s.push(``)
  s.push(`  articles Article[]`)
  s.push(`}`)
  s.push(``)
  s.push(`// ============ AGENT PROFILE ============`)
  s.push(`model AgentProfile {`)
  s.push(`  id        String   @id @default(cuid())`)
  s.push(`  userId    String   @unique`)
  s.push(`  name      String`)
  s.push(`  title     String?`)
  s.push(`  photo     String?`)
  s.push(`  whatsapp  String`)
  s.push(`  email     String?`)
  s.push(`  bio       String?`)
  s.push(`  areaSpec  String?`)
  s.push(`  isActive  Boolean  @default(true)`)
  s.push(`  sortOrder Int      @default(0)`)
  s.push(`  createdAt DateTime @default(now())`)
  s.push(`  updatedAt DateTime @updatedAt`)
  s.push(``)
  s.push(`  user User @relation(fields: [userId], references: [id])`)
  s.push(``)
  s.push(`  @@index([isActive])`)
  s.push(`}`)
  s.push(``)
  s.push(`// ============ WEBSITE SETTINGS ============`)
  s.push(`model WebsiteSetting {`)
  s.push(`  id    String @id @default(cuid())`)
  s.push(`  key   String @unique`)
  s.push(`  value String`)
  s.push(`  group String @default("general")`)
  s.push(`  createdAt DateTime @default(now())`)
  s.push(`  updatedAt DateTime @updatedAt`)
  s.push(``)
  s.push(`  @@index([group])`)
  s.push(`}`)
  s.push(``)
  s.push(`// ============ MEDIA ============`)
  s.push(`model Media {`)
  s.push(`  id        String   @id @default(cuid())`)
  s.push(`  filename  String`)
  s.push(`  url       String`)
  s.push(`  mimeType  String`)
  s.push(`  size      Int      @default(0)`)
  s.push(`  altText   String?`)
  s.push(`  folder    String   @default("/")`)
  s.push(`  deletedAt DateTime?`)
  s.push(`  createdAt DateTime @default(now())`)
  s.push(`  updatedAt DateTime @updatedAt`)
  s.push(``)
  s.push(`  @@index([folder])`)
  s.push(`}`)
  s.push(``)
  s.push(`// ============ ACTIVITY LOG ============`)
  s.push(`model ActivityLog {`)
  s.push(`  id        String   @id @default(cuid())`)
  s.push(`  userId    String`)
  s.push(`  action    String`)
  s.push(`  entity    String?`)
  s.push(`  entityId  String?`)
  s.push(`  details   String?`)
  s.push(`  ipAddress String?`)
  s.push(`  createdAt DateTime @default(now())`)
  s.push(``)
  s.push(`  user User @relation(fields: [userId], references: [id])`)
  s.push(``)
  s.push(`  @@index([userId])`)
  s.push(`  @@index([action])`)
  s.push(`  @@index([createdAt])`)
  s.push(`}`)

  return s.join('\n')
}
